title: Microbiome Workshop
description: Online materials for the DOE Inter-BRC Microbiome Workshop
theme: just-the-docs

url: https://www.germslab.org/interbrc-microbiome/

aux_links:
  Home Page: https://www.germslab.org/interbrc-microbiome/
