title: Inter-BRC Workshop
description: Online materials for the DOE Inter-BRC Workshop
theme: just-the-docs

url: https://www.germslab.org/interbrc-microbiome/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
